name: Trigger auto deployment for tanchishe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tanchishe-AutoDeployTrigger-211c6dbe-02ff-4660-b958-dc7b8a325aca.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TANCHISHE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TANCHISHE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TANCHISHE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: tanchishe.azurecr.io
          registryUsername: ${{ secrets.TANCHISHE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TANCHISHE_REGISTRY_PASSWORD }}
          containerAppName: tanchishe
          resourceGroup: tanchishe
          imageToBuild: tanchishe.azurecr.io/tanchishe:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


